CFLAGS=-std=c11 -pedantic -Wall -Wvla -Werror -Wno-unused-variable -D_DEFAULT_SOURCE

all: server client testmult

server: utils_v1.o server.o
	cc $(CFLAGS) -o server server.o utils_v1.o

client: utils_v1.o client.o
	cc $(CFLAGS) -o client client.o utils_v1.o

testmult: utils_v1.o testmult.o
	cc $(CFLAGS) -o testmult testmult.o utils_v1.o

server.o: utils_v1.h server.c
	cc $(CFLAGS) -c server.c

client.o: utils_v1.h client.c
	cc $(CFLAGS) -c client.c

testmult.o: utils_v1.h testmult.c
	cc $(CFLAGS) -c testmult

utils_v1.o: utils_v1.c utils_v1.h
	cc $(CFLAGS) -c utils_v1.c


clean:
	rm -f *o
	rm -f server
	rm -f client
	rm -f testmult
	ipcrm -a